---
environment:
  source: git://github.com/puppetlabs/control-repo.git
  version: 1.0.0

modules:
  - puppetlabs/stdlib:
      version: 4.16.0
      type:    forge

  - puppetlabs/apache:
      version: 1.9.0
      type:    forge

  - lwf/remote_file:
      version: 1.1.0
      type:    forge

  - tse/tse_admins:
      version: c2efab9e
      type:    git
